server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource  # 使用druid连接池
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true
    username: root
    password: Asd09876%
  redis:
     database: 0
     host: 127.0.0.1
     port: 6379
     password: Asd09876%
     timeout: 1000 # 连接超时时间
     jedis:
       pool:
        max-active: 8 # 最大连接数
        max-wait: -1  # 最大阻塞等待时间（负数表示没有限制）
        max-idle: 5 # 最大空闲连接数
        min-idle: 0 # 最小空闲连接数


logging:
  path: /data/eden-dubbo/logs
  level:
    root: info
    com.alibaba: error
    org.apache: error
    # SQL日志打印 开发环境启动
    com.eden.mid.mapper: debug